title: Ben JJ Walker
logo: /assets/img/work-photo_circle.png
description: I am an evolutionary ecologist with an interest in broadscale macroecological approaches, animal communication, statistical modelling, and applied outcomes of ecological and environmental management.
[Contact me](mailto:bjjwalker1@gmail.com)
#show_downloads: true
theme: jekyll-theme-minimal
