title: Ben JJ Walker
logo: /assets/img/work-photo_circle.png
#description: [Contact me](mailto:bjjwalker1@gmail.com)
#show_downloads: true
theme: jekyll-theme-minimal
nav:
  - title: Publications
    url: publication/Walker2024vertebrates/
    subnav:
      - title: Heroku
        url: publication/Walker2024vertebrates/
  - title: Contact
    url: mailto:bjjwalker1@gmail.com
